### ISSUE TITLE
Header has non UTF8 Characters.

### ISSUE THREAD

**Issue by TheRojam** [style-cheat/css#2]
![wrong head](https://pixelfed.social/storage/m/2f379dea1475aae71ee95f89a049885298819585/c7b26653e1de747932be5943422e54114fc3bfaf/6zzG1Wwq208Tn1hYwEdQ451qRe68mOId8ospNGol.png)
I just have cloned this and have unrecognized headers.

![](https://pixelfed.social/storage/m/2f379dea1475aae71ee95f89a049885298819585/c7b26653e1de747932be5943422e54114fc3bfaf/P6TOKeEtrQy7HL8s0Jdly8FynGe3AIumlvATbTdy.png)
its this is in line  22

in my vim it looks this way:
```
18   <header id="header" role="banner" class="bg-primary">
19     <section id="marque" class="container text-center">
20       <h1 class="heading-1">Style-Cheat CSS</h1>
21       <p>Just another CSS Framework.</p>
22       <h1>�~I�~K�~H�~J�~_~E~P�~_~E~Q</h1>
23     </section> <!-- /#marque -->
24   </header> <!-- /#header -->
```

**Comment by TheRojam** [comment]
@daniel-wtd please take a look

**Comment by daniel-schier** [comment]
funny, it should be "Unicode U+2B88". will have a look

**Comment by daniel-schier** [comment]
issue is addressed and i will replace the chars with the new svg logo
